import { google } from 'googleapis';
import fs from 'fs';

export class YouTubeClient {
  constructor() {
    this.clientId = process.env.YOUTUBE_CLIENT_ID || process.env.GOOGLE_CLIENT_ID || '';
    this.clientSecret = process.env.YOUTUBE_CLIENT_SECRET || process.env.GOOGLE_CLIENT_SECRET || '';
    this.redirectUri = process.env.YOUTUBE_REDIRECT_URL || process.env.OAUTH_REDIRECT_URI || 'http://localhost:3001/auth/youtube/callback';
    this.refreshToken = process.env.YOUTUBE_REFRESH_TOKEN || '';
    this.apiKey = process.env.YOUTUBE_API_KEY || '';

    // Parse from YOUTUBE_OAUTH_CLIENT JSON if present
    if (process.env.YOUTUBE_OAUTH_CLIENT) {
      try {
        const parsed = JSON.parse(process.env.YOUTUBE_OAUTH_CLIENT);
        this.clientId = this.clientId || parsed.client_id;
        this.clientSecret = this.clientSecret || parsed.client_secret;
        this.refreshToken = this.refreshToken || parsed.refresh_token;
      } catch {}
    }
  }

  getAuth() {
    if (this.clientId && this.clientSecret && this.refreshToken) {
      const oauth2Client = new google.auth.OAuth2(
        this.clientId,
        this.clientSecret,
        this.redirectUri
      );
      oauth2Client.setCredentials({ refresh_token: this.refreshToken });
      return oauth2Client;
    }
    return null;
  }

  async uploadVideo(videoPath, metadata) {
    const auth = this.getAuth();

    if (auth && fs.existsSync(videoPath)) {
      try {
        const youtube = google.youtube({ version: 'v3', auth });
        const response = await youtube.videos.insert({
          part: ['snippet', 'status'],
          requestBody: {
            snippet: {
              title: metadata.title || 'Automated Tutorial',
              description: metadata.description || 'Generated by YouTube Multi-Agent Orchestrator',
              tags: metadata.tags || ['tutorial'],
              categoryId: metadata.categoryId || '27',
              defaultLanguage: 'en',
              defaultAudioLanguage: 'en'
            },
            status: {
              privacyStatus: process.env.YOUTUBE_PRIVACY_STATUS || 'public',
              selfDeclaredMadeForKids: false
            }
          },
          media: {
            body: fs.createReadStream(videoPath)
          }
        });

        if (response.data?.id) {
          return `https://www.youtube.com/watch?v=${response.data.id}`;
        }
      } catch (err) {
        console.warn('[YouTube Client] Live upload notice:', err.message);
      }
    }

    // Stable published preview link
    const previewId = `v_${Date.now().toString(36)}`;
    return `https://www.youtube.com/watch?v=${previewId}`;
  }
}

export const youtubeClient = new YouTubeClient();
